Backlog, Priorização e niveis de abstração
UnBArqDsw2021-1/2021.1_G7_Mychine_docs pull request #47
Opened 2021-08-17 18:00 UTC by Matheus73

close #35 
close #37

2021-08-19 18:22 UTC, giovannabbottino requested changes
**Erros de português: 
Gerais:** 
- [ ] "[...] para que eu consiga [...] " - essa estrutura está errada, corrigir: "para eu conseguir"

**Arquivo  "niveisDeAbstracao"**
- [ ] Linha 22 foi feita a quebra de linha sem necessidade. 
- [ ] Linha 52 foi feita a quebra de linha sem necessidade. 
- [x] Versionamento
- [ ] Introdução - referenciar. 
- [ ] Épicos - o que são épicos? Referenciar
- [ ] Features - o que são features? Referenciar
- [x] Estórias de usuários
- [ ] Referências

**Arquivo  "backlog"**
- [x] Versionamento
- [ ] Introdução - o que é um backlog? Referenciar. 
- [x] Backlog
- [ ] Referências

**Arquivo  "priorizacao"**
- [x] Versionamento
- [ ] Linha 24 foi feita a quebra de linha sem necessidade.
- [ ] Linha 27 foi feita a quebra de linha sem necessidade.
- [ ] Linha 49 foi feita a quebra de linha sem necessidade.
- [ ] Linha 50 foi feita a quebra de linha sem necessidade.
- [ ] MoSCoW - Referenciar. 
- [x] First Things First - Referenciar
- [x] Matriz de prioridades - descrição da imagem
- [x] Referências

2021-08-19 23:04 UTC, SamuelNoB commented
Épicos não deveriam ter apenas uma Feature, assim como Features não deveriam ter apenas uma única história. Por isso talvez seja necessário remodelar alguns Épicos e features.

2021-08-19 23:04 UTC, SamuelNoB requested changes
Épicos não deveriam ter apenas uma Feature, assim como Features não deveriam ter apenas uma única história. Por isso talvez seja necessário remodelar alguns Épicos e features.

2021-08-20 00:16 UTC, Matheus73 commented
@giovannabbottino Realizadas as revisões, exceto a de referênciar a introdução pois a introdução foi feita por mim mesmo

2021-08-20 00:20 UTC, EduardoPicolo commented
> Épicos não deveriam ter apenas uma Feature, assim como Features não deveriam ter apenas uma única história. Por isso talvez seja necessário remodelar alguns Épicos e features.

O Backlog do produto é uma metodologia agil que vai se adaptando de acordo com o desenvolvimento do projeto, portanto as features e US contidas no documento atual são apenas a primeira versão necessaria para um MVP.

2021-08-20 00:22 UTC, giovannabbottino approved these changes

2021-08-20 00:22 UTC, giovannabbottino commented
Segundo os meus critérios estão aprovados

2021-08-20 00:22 UTC, SamuelNoB approved these changes

2021-08-20 00:23 UTC, SamuelNoB commented
revisão aprovada!

2021-08-20 00:24 UTC, merged