Diagrama entidade relacionamento
UnBArqDsw2021-1/2021.1_G7_Mychine_docs pull request #50
Opened 2021-08-19 21:54 UTC by Sayuck

2021-08-19 22:13 UTC, kessJhones requested changes
Falta referências.

2021-08-19 22:27 UTC, kessJhones submitted a review, later dismissed

2021-08-19 22:41 UTC, SamuelNoB reviewed
Talvez seja necessário adicionar atributos de controle para as tabelas do DER como CreatedDate e UpdatedDate.

2021-08-19 23:13 UTC, SamuelNoB requested changes
Talvez seja necessário adicionar atributos de controle para as tabelas do DER como CreatedDate e UpdatedDate.

2021-08-21 13:10 UTC, SamuelNoB approved these changes
atributos foram adicionados e com isso não há mais problemas no PR

2021-08-21 14:46 UTC, kessJhones approved these changes

2021-08-21 14:46 UTC, merged