Decorator
UnBArqDsw2021-1/2021.1_G7_Mychine_docs pull request #92
Opened 2021-09-17 00:04 UTC by JongaMatos

#91

2021-09-18 21:01 UTC, Sayuck approved these changes
Tudo ok!

2021-09-18 21:32 UTC, igorq937 commented
Só ficou faltando o exemplo de modelagem.

2021-09-18 22:04 UTC, giovannabbottino requested changes
Conceitos devem ter ligação com referências. As referências devem ter links clicáveis.

2021-09-20 01:13 UTC, giovannabbottino approved these changes

2021-09-20 03:00 UTC, Matheus73 reviewed
:art: Revisado

2021-09-20 03:01 UTC, Matheus73 approved these changes

2021-09-20 11:21 UTC, merged