Observer
UnBArqDsw2021-1/2021.1_G7_Mychine_docs pull request #94
Opened 2021-09-18 20:17 UTC by Sayuck

2021-09-18 20:57 UTC, igorq937 approved these changes
Aprovado!

2021-09-18 22:06 UTC, giovannabbottino requested changes
Conceitos devem ter ligação com referências. As referências devem ter links clicáveis. Não esqueça de explicar os exemplos

2021-09-20 03:03 UTC, Matheus73 approved these changes
:art: Tudo certo!

2021-09-20 11:13 UTC, kessJhones approved these changes

2021-09-20 11:52 UTC, SamuelNoB approved these changes

2021-09-20 11:53 UTC, giovannabbottino approved these changes

2021-09-20 11:54 UTC, merged